WEB/config/routes.rb
Photobooth::Application.routes.draw do
  
  resources :photos do
    member do
      put :toggle_published
    end
  end

  devise_for :admins
  
  match '/cam' => 'photos#cam'
  match '/camerasnap' => 'photos#camerasnap', :via => :post
  
  root :to => "photos#cam"

end

WEB/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

WEB/app/models/photo.rb
class Photo < ActiveRecord::Base
    attr_accessible :title, :image
    
    has_attached_file :image, :styles => {
									      	:micro=> "150x100#",
									      	:thumb=> "160x160#",
									      	:iphone => "320x320>",
									      	:large => "800x800>"},
									      :default_style => :large,
									      :url => "/photos/:basename_:style.:extension",
									      :path => ":rails_root/public/photos/:basename_:style.:extension"
		
end

WEB/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :prepare_for_mobile

  private

  def mobile_device?
    request.user_agent =~ /Mobile|webOS/
  end
  
  helper_method :mobile_device?

  def prepare_for_mobile
    request.format = :mobile if mobile_device?
  end
end

WEB/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  protect_from_forgery :except => :camerasnap
  
  respond_to :html, :xml, :json
  
  def index
    if mobile_device?
      @photos = Photo.all
    else
      @photos = Photo.page(params[:page]).per(20)
    end
    respond_with @photos
  end

  def show
    @photo = Photo.find(params[:id])
    respond_with @photo
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(params[:photo])
    if @photo.save
      flash[:notice] = "Successfully created photo."
      redirect_to @photo
    else
      render :action => 'new'
    end
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(params[:photo])
      flash[:notice] = "Successfully updated photo."
      redirect_to photo_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    flash[:notice] = "Successfully destroyed photo."
    redirect_to photos_url
  end
  
  def cam
    if mobile_device?
      redirect_to photos_path
    else
      render :layout => 'camera'
    end
  end
   
  def camerasnap
	  #associate the param sent by Flex (content) to a variable
	  file_data = params[:content]     
	 
	  #Decodes our Base64 string sent from Flex
	  img_data = Base64.decode64(file_data)
	  
	  dateTime = Time.new
    timestamp = dateTime.to_time.to_i
      
	  #Set an image filename, with .jpg extension
	  img_filename = "tmp/#{timestamp}.jpg"
	 
	  #Opens the "example_name.jpg" and populates it with "img_data" (our decoded Base64 send from Flex)
	  img_file = File.open(img_filename, "wb") { |f| f.write(img_data) }
	 
	  @photo = Photo.create do |photo|
      photo.title = timestamp
      photo.image = File.open(img_filename)
    end
    
    File.delete(img_filename)
    
    if @photo.save
      render :xml => @photo, :status => :created, :location => @photo
     # render :json => { :status => :ok, :message => "Success!", :html => "...insert html..." }.to_json
    else
      render :xml => @photo.errors, :status => :unprocessable_entity
      #render :json => { :status => :error, :message => "Failure!", :html => "...insert html..." }.to_json
    end
    
  end
  
  def toggle_published
    @photo = Photo.find(params[:id])
    @photo.toggle!(:published)

    redirect_to photos_url
  end
  
end

WEB/app/helpers/application_helper.rb
module ApplicationHelper
end

WEB/app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

WEB/app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

WEB/app/helpers/photos_helper.rb
module PhotosHelper
  
  def pub_status(published)
    if published == true
      'Un-Publish'
    else
      'Publish'
    end
  end
  
end

WEB/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag "application" %>
	<%= stylesheet_link_tag "/javascripts/fancybox/jquery.fancybox-1.3.4.css" %>
	
    <%= javascript_include_tag :defaults %>
	<%= javascript_include_tag 'fancybox/jquery.fancybox-1.3.4.pack' %>
	
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
	
      <% flash.each do |name, msg| %>
		<%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
	
      <%= content_tag :h1, yield(:title) if show_title? %>

      <%= yield %>

    </div>
  </body>
</html>

WEB/app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= h(yield(:title) || "Untitled") %></title>
	<meta name="apple-mobile-web-app-capable" content="yes">
	<link rel="apple-touch-icon-precomposed" href="/images/photobooth_icon.png"/>
    <%= stylesheet_link_tag "/javascripts/jquery.mobile-1.0a4.1/jquery.mobile-1.0a4.1.min.css" %>
	<%= stylesheet_link_tag 'mobile' %>
    <%= javascript_include_tag :defaults, "jquery.mobile-1.0a4.1/jquery.mobile-1.0a4.1.min.js" %>
    <%= yield(:head) %>
	<script type="text/javascript">
		$(document).bind("mobileinit", function(){
		  $.extend(  $.mobile , {
		    ajaxEnabled: false
		  });
		});
		
		$(document).ready(function() {
			$('#refresh_photos').live('tap', function() {
				$('#Page ul').listview('refresh');
			});
		});
	</script>
  </head>
  <body>
    <div class="current">
      <%- if show_title? -%>
      <div class="toolbar">
        <%= link_to "Back", nil, :class => "back" unless current_page? root_path %>
        <h1><%=h yield(:title) %></h1>
        <%= link_to "Full Site", root_url(:mobile => 0), :class => "button", :rel => "external" %>
        <%= yield(:toolbar) %>
      </div>
      <%- end -%>
      
      <% unless flash.empty? %>
        <div class="info">
        <%- flash.each do |name, msg| -%>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <%- end -%>
        </div>
      <% end %>
    
      <%= yield %>
    </div>
  </body>
</html>

WEB/app/views/layouts/camera.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Photo Booth" %></title>

    <%= stylesheet_link_tag "application" %>
	
    <%= javascript_include_tag :defaults %>
	<%= javascript_include_tag 'swfobject' %>
	<script type="text/javascript">
		var flashvars = {};

		var params = {};
		params.menu = "false";
		params.allowfullscreen = "true";
		params.allownetworking = "all";

		var attributes = {};
		attributes.id = "myCamera";
		attributes.name = "myCamera";

		swfobject.embedSWF("swfs/PhotoBooth.swf", "myCamera", "1024", "768", "10.1.0", "expressInstall.swf", flashvars, params, attributes);
	</script>
	
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
		<div id="camera">
			<%= yield %>
		</div>
  </body>
</html>

WEB/app/views/photos/_form.html.erb
<%= form_for @photo, :html => { :multipart => true } do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :published %>
    <%= f.check_box :published %>
  </p>
  <p>
  	<%= f.label :image %>
  	<%= f.file_field :image %>
  </p>
  <p><%= f.submit %></p>
<% end %>

WEB/app/views/photos/_form.mobile.erb
<%= form_for @photo, :html => { :multipart => true } do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :published %>
    <%= f.check_box :published %>
  </p>
  <p>
  	<%= f.label :image %>
  	<%= f.file_field :image %>
  </p>
  <p><%= f.submit %></p>
<% end %>

WEB/app/views/photos/cam.html.erb
<% title "Photo Booth" %>

<div id="myCamera">
	<h1>Alternative content</h1>
	<p>
		<a href="http://www.adobe.com/go/getflashplayer">
			<img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" />
		</a>
	</p>
</div>

<p><%= link_to "Photo List", photos_path %></p>

WEB/app/views/photos/edit.html.erb
<% title "Edit Photo" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @photo %> |
  <%= link_to "View All", photos_path %>
</p>

WEB/app/views/photos/index.html.erb
<% title "Photos" %>

<table>
  <tr>
    <th>Title</th>
    <th>Image</th>
    <th>Published</th>
  </tr>
  <% for photo in @photos %>
    <tr>
      <td><%= photo.title %></td>
      <td><%= link_to image_tag(photo.image.url(:micro)), photo.image.url(:large), :class => 'fancy', :rel => 'photo_group' %></td>
      <td><%= link_to photo.published.to_s, toggle_published_photo_path(photo), :method => :put, :class => photo.published.to_s %></td>
      <td>
        <%= link_to "Show", photo %> | 
        <%= link_to "Edit", edit_photo_path(photo) %> | 
        <%= link_to "Destroy", photo, :confirm => 'Are you sure?', :method => :delete %>
      </td>
    </tr>
  <% end %>
</table>

<%= paginate @photos %>

<p><%= link_to "New Photo", new_photo_path(photo) %> | <%= link_to 'Camera', '/cam' %></p>

WEB/app/views/photos/index.mobile.erb
<div  data-role="page" data-add-back-btn="false">
	<div data-role="header" data-position="fixed">
		<h1>Photos</h1>
		<%= link_to 'Home', photos_path, :id => 'refresh_photos', :class => "ui-btn-right", 'data-icon' => "refresh", 'data-iconpos' => "notext", 'data-transition' => "none" %>
	</div>
	
	<div data-role="content">
		<ul data-role="listview" data-inset="false" data-theme="c" data-dividertheme="b">
			<% for photo in @photos %>
				<li><a href="<%= photo_path(photo) %>">
					<%= image_tag(photo.image.url(:thumb)) %>
					<%= 'Published: ' + photo.published.to_s %>
					</a>
				</li>
			<% end %>
		</ul>
	</div>
</div>

WEB/app/views/photos/new.html.erb
<% title "New Photo" %>

<%= render 'form' %>

<p><%= link_to "Back to List", photos_path %></p>

WEB/app/views/photos/new.mobile.erb
<div  data-role="page">
	<div data-role="header">
		<h1>New Photo</h1>
	</div>
	
	<div data-role='content'>
		<%= render 'form' %>
	</div>

	<button type="submit" data-theme="b">
		<%= link_to "Back to List", photos_path %>
	</button>

</div>

WEB/app/views/photos/show.html.erb
<% title "Photo" %>

<p>
  <strong>Title:</strong>
  <%= @photo.title %>
</p>

<p>
	<strong>Image:</strong><br />
	<%= image_tag @photo.image.url(:large) %>
</p>

<p>
  <%= link_to "Edit", edit_photo_path(@photo) %> |
  <%= link_to "Destroy", @photo, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", photos_path %>
</p>

WEB/app/views/photos/show.mobile.erb
<div data-role="page" data-fullscreen="true">
	<div data-role="header" data-position="fixed">
		<%= link_to 'Home', photos_path, 'data-icon' => "back", 'data-direction' => "reverse" %>
		<h1>Photos</h1>
	</div>
	
	<div data-role="content" style="padding:0px;">
		<%= image_tag @photo.image.url(:large), :class => 'photo' %>
	</div>
	
	<div data-role="footer" data-position="fixed">
		<div data-role="navbar">
			<ul>
				<li><%= link_to pub_status(@photo.published), toggle_published_photo_path(@photo), :method => :put, 'data-icon' => 'check' %></li>
				<li><%= link_to "Destroy", @photo, :confirm => 'Are you sure?', :method => :delete, 'data-icon' => 'delete' %></li>
			</ul>
		</div>
	</div>
</div>